name: Send Terms to Kinesis

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Leer config JS
        id: config_step
        run: |
          echo "Reading JS config..."
          node -e "
            const config = require('./dev.config');
            console.log('::set-output name=env::' + config.env);
            console.log('::set-output name=region::' + config.scheduler.sqs.construct.region);
          "