name: Echo vars

on:
  workflow_dispatch:

env:
  STREAM_NAME: production
  PARTITION_KEY: new_terms_of_service_version
  AWS_REGION: us-east-1
  TERMS_PATH: "src/views/terms-of-service/index.html"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Echo vars
        run: |
          echo "STREAM_NAME: $STREAM_NAME"
          echo "PARTITION_KEY: $PARTITION_KEY"
          echo "AWS_REGION: $AWS_REGION"
          echo "TERMS_PATH: $TERMS_PATH"