name: Send new terms of service to kinesis

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Deploy - PRODUCTION
    types:
      - completed

jobs:
  send-terms-to-kinesis:
    runs-on: ubuntu-latest
    env:
      STREAM_NAME: production
      PARTITION_KEY: new_terms_of_service_version
      AWS_REGION: us-east-1
      TERMS_PATH: ./terms.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changes in terms of service
        run: |
          set -x
          git fetch origin master
          if !  git diff --name-only origin/master | grep -q "$TERMS_PATH"; then
            echo "No changes in terms of service. Exiting."
            exit 0
          fi

      - name: Send event to Kinesis (Debug)
        run: |
          TERMS=$(cat "$TERMS_PATH" | base64 -w 0)
          PAYLOAD=$(jq -n --arg terms "$TERMS" --arg timestamp "$(date +%s)" '{timestamp: $timestamp, terms: $terms}')

          echo "STREAM_NAME: $STREAM_NAME"
          echo "PARTITION_KEY: $PARTITION_KEY"
          echo "AWS_REGION: $AWS_REGION"
          echo "TERMS_PATH: $TERMS_PATH"
          echo "TERMS: $TERMS"
          echo "PAYLOAD: $PAYLOAD"

