name: Send new terms of service to kinesis

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Deploy - PRODUCTION
    types:
      - completed

jobs:
  send-terms-to-kinesis:
    runs-on: ubuntu-latest
    env:
      STREAM_NAME: production
      PARTITION_KEY: new_terms_of_service_version
      AWS_REGION: us-east-1
      TERMS_PATH: src/views/terms-of-service/index.html
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check TOS changes since last release
        id: detect_changes
        run: |
          CURRENT=$(git tag --sort=-creatordate | head -n 2 | sed -n '1p')
          PREVIOUS=$(git tag --sort=-creatordate | head -n 2 | sed -n '2p')
          FILES=$(git diff --name-only $PREVIOUS $CURRENT)
          echo "Files changed between $PREVIOUS and $CURRENT:"
          echo "$FILES"
          if echo $FILES | grep -q "$TERMS_PATH"; then
            echo "$TERMS_PATH was modified."
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "$TERMS_PATH was NOT modified."
            echo "changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Send event to Kinesis (Debug)
        if: steps.detect_changes.outputs.changes == 'true'
        run: |
          TERMS=$(cat "$TERMS_PATH" | base64 -w 0)
          PAYLOAD=$(jq -n --arg terms "$TERMS" --arg timestamp "$(date +%s)" '{timestamp: $timestamp, terms: $terms}')

          echo "STREAM_NAME: $STREAM_NAME"
          echo "PARTITION_KEY: $PARTITION_KEY"
          echo "AWS_REGION: $AWS_REGION"
          echo "TERMS_PATH: $TERMS_PATH"
          echo "TERMS: $TERMS"
          echo "PAYLOAD: $PAYLOAD"

