name: CI

on:
  push:
    branches: [ "json-action" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read config version
        id: version_step
        run: |
          version=$(jq -r '.termsOfService.version' ./dev.config)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Read Terms text
        id: terms_step
        run: |
          terms=$(cat ./terms.md | base64 -w 0)
          echo "terms=$terms" >> $GITHUB_OUTPUT

      - name: Create event
        run: |
          echo "La versión es ${{ steps.version_step.outputs.version }}"
          echo "Los terms son: ${{ steps.terms_step.outputs.terms }}" | base64 -d
