name: Version bump reminder

on:
  pull_request:
    paths:
      - "terms.md"

  workflow_dispatch:

jobs:
  create-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create comment
        run: |
          echo "⚠️ Terms of service have changed. Please remember to bump the version in dev.config and update the changelog." > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}